user:
  name: Rishika

reddit:
  enabled: true
  subreddits:
    - developersIndia
    - ENGLISH
  include_fields:
    - tech
    - internship
    - career
    - self_development
    - learning
    - english
    - dsa
  exclude_fields:
    - politics
    - shitpost
    - nsfw
    - relationship
    - rant
    - vent
    - hate
    - meme

email:
  enabled: true
  important_senders:
    - "@college.edu"
    - "@university.edu"
    - "@company.com"
  blacklisted_senders:
    - "noreply@delhivery.com"
    - "noreply@redditmail.com"
    - "noreply@swiggy.in"
    - "hello@codingninjas.com"
  important_keywords:
    - tech
    - internship
    - career
    - self_development
  ignore_keywords:
    - promotions
    - sales
    - discounts
    - myntra
    - meesho
    - flipkart
  max_age_days: 7

general:
  min_content_length: 20
  language: en